const bookArray = [
  {
    "title": "The Glass Meridian",
    "author": "Elena Hartwell",
    "isbn": "9780143123456",
    "publicationYear": 2018,
    "genres": ["Literary Fiction", "Drama"],
    "description": "A quiet exploration of grief and renewal set in a fading coastal town.",
    "pageCount": 312,
    "averageRating": 4.1,
    "numberOfRatings": 8421
  },
  {
    "title": "Orbit of Ash",
    "author": "Marcus Keene",
    "isbn": "9780316498765",
    "publicationYear": 2021,
    "genres": ["Science Fiction", "Thriller"],
    "description": "Survivors of a shattered space station uncover a conspiracy that spans galaxies.",
    "pageCount": 428,
    "averageRating": 4.3,
    "numberOfRatings": 15632
  },
  {
    "title": "Beneath the Juniper Moon",
    "author": "Lila Moreno",
    "isbn": "9780062987451",
    "publicationYear": 2016,
    "genres": ["Romance", "Contemporary"],
    "description": "Two strangers find love and healing during one unforgettable summer.",
    "pageCount": 287,
    "averageRating": 3.9,
    "numberOfRatings": 10244
  },
  {
    "title": "The Iron Archivist",
    "author": "Thomas Caldwell",
    "isbn": "9780525567892",
    "publicationYear": 2019,
    "genres": ["Fantasy", "Adventure"],
    "description": "A reluctant scholar guards secrets powerful enough to end an empire.",
    "pageCount": 512,
    "averageRating": 4.5,
    "numberOfRatings": 23110
  },
  {
    "title": "Signal in the Noise",
    "author": "Priya Nandakumar",
    "isbn": "9781250246813",
    "publicationYear": 2020,
    "genres": ["Nonfiction", "Technology"],
    "description": "An accessible look at how data shapes modern decision-making.",
    "pageCount": 364,
    "averageRating": 4.0,
    "numberOfRatings": 5342
  },
  {
    "title": "The Last Orchard",
    "author": "Henry Wilkes",
    "isbn": "9781982134579",
    "publicationYear": 2015,
    "genres": ["Historical Fiction"],
    "description": "A farming family struggles to survive during a time of great change.",
    "pageCount": 401,
    "averageRating": 4.2,
    "numberOfRatings": 6789
  },
  {
    "title": "Cinders of the Crown",
    "author": "Ava Sinclair",
    "isbn": "9780593442210",
    "publicationYear": 2023,
    "genres": ["Fantasy", "Politics"],
    "description": "A deposed queen plots her return in a land ruled by intrigue.",
    "pageCount": 589,
    "averageRating": 4.6,
    "numberOfRatings": 19450
  },
  {
    "title": "The Narrow Bridge",
    "author": "Samuel Price",
    "isbn": "9780385549123",
    "publicationYear": 2012,
    "genres": ["Mystery", "Crime"],
    "description": "A small-town detective reopens a cold case with dangerous consequences.",
    "pageCount": 336,
    "averageRating": 3.8,
    "numberOfRatings": 9123
  },
  {
    "title": "Wild Arithmetic",
    "author": "Joanne Liu",
    "isbn": "9780262045129",
    "publicationYear": 2022,
    "genres": ["Nonfiction", "Science"],
    "description": "Finding unexpected beauty in mathematics and the natural world.",
    "pageCount": 278,
    "averageRating": 4.4,
    "numberOfRatings": 3211
  },
  {
    "title": "Echoes of Red Sand",
    "author": "Nikhil Rao",
    "isbn": "9780756412349",
    "publicationYear": 2017,
    "genres": ["Science Fiction"],
    "description": "On a colonized Mars, old Earth conflicts refuse to stay buried.",
    "pageCount": 455,
    "averageRating": 4.1,
    "numberOfRatings": 11876
  },
  {
    "title": "The Paper Violin",
    "author": "Miriam Feld",
    "isbn": "9780393356784",
    "publicationYear": 2014,
    "genres": ["Literary Fiction"],
    "description": "Music binds generations of a family marked by exile and hope.",
    "pageCount": 298,
    "averageRating": 4.0,
    "numberOfRatings": 6044
  },
  {
    "title": "Stormward",
    "author": "Derek Holloway",
    "isbn": "9780765389120",
    "publicationYear": 2011,
    "genres": ["Fantasy", "Epic"],
    "description": "Warriors defend the realm using ancient weather-bound magic.",
    "pageCount": 721,
    "averageRating": 4.3,
    "numberOfRatings": 14322
  },
  {
    "title": "A Brief History of Almost Everything Else",
    "author": "Calvin Brooks",
    "isbn": "9780307476711",
    "publicationYear": 2010,
    "genres": ["Nonfiction", "History"],
    "description": "Short essays connecting overlooked moments in world history.",
    "pageCount": 389,
    "averageRating": 3.7,
    "numberOfRatings": 4881
  },
  {
    "title": "Night Market Neon",
    "author": "Renee Okafor",
    "isbn": "9781250812345",
    "publicationYear": 2024,
    "genres": ["Urban Fantasy"],
    "description": "Magic and crime collide in a city that never truly sleeps.",
    "pageCount": 402,
    "averageRating": 4.5,
    "numberOfRatings": 2876
  },
  {
    "title": "The Long Descent",
    "author": "Victor Hale",
    "isbn": "9781451678902",
    "publicationYear": 2009,
    "genres": ["Thriller"],
    "description": "A climber’s survival story turns into a psychological nightmare.",
    "pageCount": 351,
    "averageRating": 3.9,
    "numberOfRatings": 7602
  },
  {
    "title": "Ink and Bone Letters",
    "author": "Sofia Laurent",
    "isbn": "9780547923458",
    "publicationYear": 2018,
    "genres": ["Young Adult", "Fantasy"],
    "description": "Teen scribes discover their words can reshape reality.",
    "pageCount": 374,
    "averageRating": 4.2,
    "numberOfRatings": 18211
  },
  {
    "title": "The Silent Latitude",
    "author": "Owen Marsh",
    "isbn": "9780374532217",
    "publicationYear": 2013,
    "genres": ["Literary Fiction"],
    "description": "Isolation and obsession aboard an Antarctic research vessel.",
    "pageCount": 329,
    "averageRating": 3.6,
    "numberOfRatings": 4219
  },
  {
    "title": "Practical Alchemy",
    "author": "Beatrice Knox",
    "isbn": "9781627794561",
    "publicationYear": 2020,
    "genres": ["Fantasy", "Cozy"],
    "description": "Everyday problems solved with gentle magic and tea.",
    "pageCount": 241,
    "averageRating": 4.4,
    "numberOfRatings": 9678
  },
  {
    "title": "The Fifth Index",
    "author": "Arjun Patel",
    "isbn": "9780134856723",
    "publicationYear": 2019,
    "genres": ["Nonfiction", "Economics"],
    "description": "Rethinking how societies measure progress and well-being.",
    "pageCount": 412,
    "averageRating": 3.8,
    "numberOfRatings": 3567
  },
  {
    "title": "Ravens at Dusk",
    "author": "Clara Osei",
    "isbn": "9781408891234",
    "publicationYear": 2017,
    "genres": ["Mystery"],
    "description": "A journalist investigates a pattern of deaths in a remote village.",
    "pageCount": 305,
    "averageRating": 4.1,
    "numberOfRatings": 8890
  },
  {
    "title": "The Copper Sky",
    "author": "James R. Ellison",
    "isbn": "9780553419987",
    "publicationYear": 2015,
    "genres": ["Science Fiction", "Dystopian"],
    "description": "Survival under a polluted dome tests the limits of humanity.",
    "pageCount": 468,
    "averageRating": 4.0,
    "numberOfRatings": 13245
  },
  {
    "title": "Threading the Labyrinth",
    "author": "Helena Cruz",
    "isbn": "9780743278910",
    "publicationYear": 2008,
    "genres": ["Mythology", "Fantasy"],
    "description": "Ancient myths retold through the eyes of forgotten women.",
    "pageCount": 522,
    "averageRating": 4.3,
    "numberOfRatings": 10112
  },
  {
    "title": "Small Hours, Big City",
    "author": "Noah Bennett",
    "isbn": "9780399178458",
    "publicationYear": 2016,
    "genres": ["Contemporary"],
    "description": "Interwoven lives unfold over one sleepless night.",
    "pageCount": 264,
    "averageRating": 3.5,
    "numberOfRatings": 2998
  },
  {
    "title": "The Bone Cartographer",
    "author": "Isabel Trent",
    "isbn": "9780765376540",
    "publicationYear": 2022,
    "genres": ["Fantasy", "Dark Fantasy"],
    "description": "A mapmaker charts lands that exist only after death.",
    "pageCount": 611,
    "averageRating": 4.7,
    "numberOfRatings": 8475
  },
  {
    "title": "Learning to Breathe Water",
    "author": "Daniel Cho",
    "isbn": "9780307389126",
    "publicationYear": 2011,
    "genres": ["Memoir"],
    "description": "An immigrant story of identity, loss, and adaptation.",
    "pageCount": 289,
    "averageRating": 4.1,
    "numberOfRatings": 5620
  },
  {
    "title": "Clockwork Harbor",
    "author": "Penelope Grant",
    "isbn": "9780763665417",
    "publicationYear": 2014,
    "genres": ["Steampunk", "Adventure"],
    "description": "Airships and automatons rule a bustling mechanical port.",
    "pageCount": 447,
    "averageRating": 4.2,
    "numberOfRatings": 11034
  },
  {
    "title": "The Ethics of Tomorrow",
    "author": "Robert Klein",
    "isbn": "9780691203459",
    "publicationYear": 2021,
    "genres": ["Nonfiction", "Philosophy"],
    "description": "Moral dilemmas emerging from rapid technological change.",
    "pageCount": 378,
    "averageRating": 3.9,
    "numberOfRatings": 2744
  },
  {
    "title": "Ashes in the Key of Blue",
    "author": "Monique Harris",
    "isbn": "9781524734568",
    "publicationYear": 2018,
    "genres": ["Literary Fiction", "Music"],
    "description": "A jazz pianist confronts the cost of artistic ambition.",
    "pageCount": 322,
    "averageRating": 4.0,
    "numberOfRatings": 4876
  },
  {
    "title": "The Wolf Census",
    "author": "Evan Miller",
    "isbn": "9780812991236",
    "publicationYear": 2019,
    "genres": ["Nonfiction", "Nature"],
    "description": "Tracking wolves to understand fragile ecosystems.",
    "pageCount": 341,
    "averageRating": 4.3,
    "numberOfRatings": 3989
  },
  {
    "title": "Mirrors of Salt",
    "author": "Ana Beltrán",
    "isbn": "9780374109129",
    "publicationYear": 2013,
    "genres": ["Poetry"],
    "description": "A collection exploring memory, body, and coastline.",
    "pageCount": 176,
    "averageRating": 3.7,
    "numberOfRatings": 1902
  },
  {
    "title": "The Last Algorithm",
    "author": "Kevin Zhou",
    "isbn": "9780735217894",
    "publicationYear": 2024,
    "genres": ["Science Fiction", "AI"],
    "description": "An engineer races to stop an intelligence beyond control.",
    "pageCount": 493,
    "averageRating": 4.4,
    "numberOfRatings": 6543
  },
  {
    "title": "Harvest of Shadows",
    "author": "Margaret O'Connell",
    "isbn": "9780062457896",
    "publicationYear": 2007,
    "genres": ["Historical Fiction", "Mystery"],
    "description": "A murder disrupts life in a famine-stricken village.",
    "pageCount": 367,
    "averageRating": 3.8,
    "numberOfRatings": 7120
  },
  {
    "title": "Blueprints for Falling",
    "author": "Aaron Feldman",
    "isbn": "9780525553215",
    "publicationYear": 2020,
    "genres": ["Contemporary", "Romance"],
    "description": "Love and ambition collide in the world of architecture.",
    "pageCount": 354,
    "averageRating": 3.9,
    "numberOfRatings": 8433
  },
  {
    "title": "The Ember Monastery",
    "author": "Tenzin Norbu",
    "isbn": "9781616209874",
    "publicationYear": 2016,
    "genres": ["Fantasy", "Spiritual"],
    "description": "Monks guard a flame said to contain a god.",
    "pageCount": 486,
    "averageRating": 4.2,
    "numberOfRatings": 5298
  },
  {
    "title": "Subtitles for Silence",
    "author": "Yara Haddad",
    "isbn": "9781910702341",
    "publicationYear": 2022,
    "genres": ["Essays"],
    "description": "Reflections on language, migration, and belonging.",
    "pageCount": 233,
    "averageRating": 4.1,
    "numberOfRatings": 2187
  },
  {
    "title": "The Verdant Machine",
    "author": "Lucas Reinhardt",
    "isbn": "9780345812340",
    "publicationYear": 2015,
    "genres": ["Science Fiction", "Ecofiction"],
    "description": "A self-aware forest challenges human expansion.",
    "pageCount": 419,
    "averageRating": 4.0,
    "numberOfRatings": 9734
  },
  {
    "title": "Maps for the Unlost",
    "author": "Natalie Pierce",
    "isbn": "9781101874562",
    "publicationYear": 2017,
    "genres": ["Self-Help"],
    "description": "Practical guidance for redefining success and purpose.",
    "pageCount": 256,
    "averageRating": 3.6,
    "numberOfRatings": 14021
  },
  {
    "title": "A Cathedral of Wind",
    "author": "Peter Lang",
    "isbn": "9780142423459",
    "publicationYear": 2006,
    "genres": ["Fantasy"],
    "description": "Nomads build cities that drift across the sky.",
    "pageCount": 603,
    "averageRating": 4.2,
    "numberOfRatings": 8845
  },
  {
    "title": "The Unfinished Atlas",
    "author": "Rachel Kim",
    "isbn": "9780593234561",
    "publicationYear": 2021,
    "genres": ["Fantasy", "Adventure"],
    "description": "Each map page opens a door to a different world.",
    "pageCount": 548,
    "averageRating": 4.5,
    "numberOfRatings": 12987
  },
  {
    "title": "Ordinary Fire",
    "author": "Stephen Moore",
    "isbn": "9780307598764",
    "publicationYear": 2012,
    "genres": ["Literary Fiction"],
    "description": "The aftermath of a tragedy in a suburban community.",
    "pageCount": 314,
    "averageRating": 3.8,
    "numberOfRatings": 4560
  },
  {
    "title": "Quantum Breadcrumbs",
    "author": "Lena Fischer",
    "isbn": "9780262539871",
    "publicationYear": 2023,
    "genres": ["Popular Science"],
    "description": "Making sense of quantum physics through everyday metaphors.",
    "pageCount": 291,
    "averageRating": 4.3,
    "numberOfRatings": 3654
  },
  {
    "title": "The River That Remembers",
    "author": "Ahmed Suleiman",
    "isbn": "9780385541233",
    "publicationYear": 2018,
    "genres": ["Historical Fiction"],
    "description": "A river witnesses centuries of love, war, and change.",
    "pageCount": 477,
    "averageRating": 4.1,
    "numberOfRatings": 7342
  },
  {
    "title": "Paper Suns",
    "author": "Emily Rhodes",
    "isbn": "9780061123457",
    "publicationYear": 2005,
    "genres": ["Young Adult"],
    "description": "Teenagers navigate friendship and loss during their final summer.",
    "pageCount": 248,
    "averageRating": 3.7,
    "numberOfRatings": 15890
  },
  {
    "title": "The Salt Librarian",
    "author": "Jonas Petrov",
    "isbn": "9781789098765",
    "publicationYear": 2024,
    "genres": ["Fantasy"],
    "description": "Books preserved in salt hold memories of vanished seas.",
    "pageCount": 534,
    "averageRating": 4.6,
    "numberOfRatings": 4123
  },
  {
    "title": "After the Applause",
    "author": "Victoria Lane",
    "isbn": "9781501167890",
    "publicationYear": 2019,
    "genres": ["Memoir", "Performing Arts"],
    "description": "A stage actor reflects on fame, failure, and reinvention.",
    "pageCount": 301,
    "averageRating": 4.0,
    "numberOfRatings": 2956
  },
  {
    "title": "Gravel and Starlight",
    "author": "Hector Alvarez",
    "isbn": "9780316574320",
    "publicationYear": 2016,
    "genres": ["Road Trip", "Literary Fiction"],
    "description": "A cross-country journey becomes a search for forgiveness.",
    "pageCount": 359,
    "averageRating": 3.9,
    "numberOfRatings": 6211
  },
  {
    "title": "The Last Snow Signal",
    "author": "Katherine Bloom",
    "isbn": "9781250909875",
    "publicationYear": 2022,
    "genres": ["Science Fiction", "Climate"],
    "description": "Scientists race to decode a message hidden in melting ice.",
    "pageCount": 467,
    "averageRating": 4.2,
    "numberOfRatings": 7089
  },
  {
    "title": "Hinterland Choir",
    "author": "Paul Vermeer",
    "isbn": "9780802123459",
    "publicationYear": 2011,
    "genres": ["Literary Fiction"],
    "description": "Voices from a remote region reveal a shared, fragile history.",
    "pageCount": 386,
    "averageRating": 3.6,
    "numberOfRatings": 3377
  },
  {
    "title": "The Hobbit (75th Anniversary Edition)",
    "author": "J.R.R. Tolkien",
    "isbn": "9780547928227",
    "publicationYear": 2012,
    "genres": ["Fantasy"],
    "description": "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure.",
    "pageCount": 320,
    "averageRating": 4.5,
    "numberOfRatings": 4500
  },
  {
    "title": "The Martian",
    "author": "Andy Weir",
    "isbn": "9780804139021",
    "publicationYear": 2014,
    "genres": ["Science Fiction", "Thriller"],
    "description": "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now he's sure he'll be the first person to die there.",
    "pageCount": 369,
    "averageRating": 4.4,
    "numberOfRatings": 319
  },
  {
    "title": "Harry Potter and the Philosopher's Stone",
    "author": "J.K. Rowling",
    "isbn": "9781338878929",
    "publicationYear": 1998,
    "genres": ["Literary Fiction", "Fantasy", "Young Adult"],
    "description": "I used the British title because I am pretentious.",
    "pageCount": 320,
    "averageRating": 0,
    "numberOfRatings": 1
  },
  {
    "title": "Harry Potter and the Chamber of Secrets",
    "author": "J.K. Rowling",
    "isbn": "9781546171409",
    "publicationYear": 2000,
    "genres": ["Literary Fiction", "Fantasy", "Young Adult"],
    "description": "J.K. Rowling is the worst.",
    "pageCount": 352,
    "averageRating": 0,
    "numberOfRatings": 1
  },
  {
    "title": "The Color of Magic: A Discworld Novel",
    "author": "Terry Pratchett",
    "isbn": "9780062225672",
    "publicationYear": 1983,
    "genres": ["Literary Fiction", "Fantasy", "Humor"],
    "description": "The well-meaning but remarkably inept wizard Rincewind encounters something hitherto unknown in the Discworld: a tourist!",
    "pageCount": 288,
    "averageRating": 4.4,
    "numberOfRatings": 27040
}
]

export default bookArray